name: 'Composite Action'
description: 'A simple composite action for my organization repo'
inputs:
  run-commands:
    description: 'The commands to run'
    required:true
runs:
  using: 'composite'
  steps:
    - name: Run commands
      shell: bash
      run: |
        ${{ inputs.run-commands }}
