name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and Deploy
        uses: ./.github/composite-actions/build-and-deploy
        with:
          repository: ${{ github.repository }}
          branch: main
          path: .
