on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello and build with node  
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: githubs-free-organization/hello-world-composite-action@main
        with:
          who-to-greet: 'Mona the Octocat'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
