name: Build and Deploy on Pull Request
on:
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and Deploy
        uses: .github/composite-actions/build-and-deploy
        with:
          repository: ${{ github.repository }}
          branch: ${{ github.event.pull_request.head.ref }}
          path: .
